version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fullstack_postgres
    restart: always
    environment:
      POSTGRES_USER: sergio
      POSTGRES_PASSWORD: sergiopass
      POSTGRES_DB: fullstackdata
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
